# Generated by Django 2.1.5 on 2019-06-23 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190612_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('Highest_degree_achieved', models.CharField(max_length=120)),
                ('cv', models.FileField(upload_to='cv/cvs')),
                ('Highest_Certtificate', models.FileField(upload_to='certificates')),
                ('cover_letter', models.FileField(upload_to='covers/letters')),
            ],
        ),
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 23, 11, 33, 36, 706232), verbose_name='date published'),
        ),
    ]
