# Generated by Django 2.1.5 on 2019-07-23 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190628_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorials',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 14, 54, 53, 527771), verbose_name='date published'),
        ),
    ]
